In [121]:
#Задача 1.
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
import numpy as np
quantity_element = int(input('Количество элементов массива '))
# p = np.arange(quantity_element,0, - 1)
# print(type(p))
z = np.arange(quantity_element)
z = z[::-1]
print(z)


Количество элементов массива 10
[9 8 7 6 5 4 3 2 1 0]


In [126]:
#Задача 2.
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
quantity_element_2 = int(input('Количество чисел для создания диагональной матрицы '))
dim = int(quantity_element_2**0.5)
if (quantity_element_2**0.5)%1 == 0:
    a = np.arange(quantity_element_2 -1, -1, - 1).reshape(dim,dim)
    print(a)
    sum_first_diagonal = sum(a[i][i] for i in range(dim))
    print('Сумма главной диагонали =', sum_first_diagonal)
    sum_second_diagonal = sum(a[i][dim - 1 - i] for i in range(dim))
    print('Сумма побочной диагонали =', sum_second_diagonal)
else:
    print('Невозможно создать диагональную матрицу')

Количество чисел для создания диагональной матрицы 16
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
Сумма главной диагонали = 30
Сумма побочной диагонали = 30


In [129]:
#Задача 3.
#Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3
import numpy as np
# коэффициенты в левой части
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
# значения в правой части
b = np.array([4, 12, -3])
x = np.linalg.solve(a, b)
print ('Корни :',x) 

Корни : [ 0.46666667  3.84444444 -5.55555556]


In [ ]:
#Задача 4.Условие.
#В материалах занятия раздел “Задача 4 домашнего задания”
Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. 
Остальные столбцы - количество покупок категорий товаров этим пользователем:
from IPython.display import Image
Image("user_matrix.JPG")


users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем 
и всеми пользователями из массива user_stats

In [95]:
# Задача 4.
import numpy as np
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

similarity_scores = users_stats.dot(next_user_stats) / (np.linalg.norm(users_stats, axis=1) * np.linalg.norm(next_user_stats))
print('Косинусное сходство с новым пользователем:',similarity_scores)
print('ID самого похожего пользователя - ',similarity_scores.argmax(axis=0)+1)

Косинусное сходство с новым пользователем: [0.2        0.84515425 0.4        0.79056942 0.4        0.
 0.         0.9486833  0.         0.        ]
ID самого похожего пользователя -  8
